#
# @Author: wjm
# @Date: 2019-10-13 21:45:10
# @LastEditTime: 2019-10-13 21:46:06
# @Description: file content
# 

name: Net
algorithm: PNN #[PANNet, PNN]
nEpochs: 2000
gpu_mode: True
save_best: True
gpus: [0, 1]
threads: 8

seed: 123
checkpoint: checkpoint
data_dir_train: ./dataset/train
data_dir_eval: ./dataset/test
source_ms: ms
source_pan: pan

pretrain:
  pretrained: False
  pre_sr: 1592134968/best.pth
  pre_folder: checkpoint

test:
  algorithm: PANNet #[PANNet, PNN]
  type: test #[test, eval]
  data_dir: ./dataset/test
  source_ms: ms
  source_pan: pan
  model: PANNet_4_1605255794/best.pth

data:
  upsacle:  4
  batch_size: 16
  patch_size: 33
  data_augmentation: False                                                                                                                                                                                               
  n_colors: 4
  rgb_range: 255
  normalize : False
  
schedule:
  lr: 1e-2
  decay: 500
  gamma: 0.1
  optimizer: SGD #[ADAM, SGD, RMSprop]
  momentum: 0.9 #SGD momentum
  beta1: 0.9 #ADAM beta
  beta2: 0.999 #ADAM beta
  epsilon: 1e-8 #ADAM epsilon
  alpha: 0.9 #RMSprop alpha
  weight_dency: 0
  gclip: 0.04
  loss: MSE #[MSE, L1]
  use_YCbCr: False

